### ISSUE TITLE
issues about the single data time

### ISSUE THREAD

**Issue by rdyan0053** [spencergritton/HADLN-Implementation#1]
I am a little confused, the paper says `The dataset consisted of 8,528 single lead ECG data recordings, and each of them is sampled at 300 Hz with a length of 9–61 s.`
![image](https://user-images.githubusercontent.com/53009617/233888484-7bcb9062-7099-465a-a629-8b4b26dce69d.png)

But when I ran the code in hadln.ipynb, I found that the x-axis of this data is 175, which is more than 61s.
![image](https://user-images.githubusercontent.com/53009617/233887860-784664b0-637a-4e11-93d1-a731459208ed.png)

**Comment by spencergritton** [comment]
It's been a bit since I've taken a look at this but like you said, initially samples were taken with lengths between 9-61 seconds. This data was then split into individual heartbeats like the one you see in the figure above. This still leaves some question about the unit of time of the x axis. If I'm remembering correctly these samples are typically measured in samples per second (Hz). As you noted, the paper claims 300Hz, the MIT BIH dataset claims 360Hz, and the PTB dataset claims up to 1000Hz. However, as mentioned later in the paper, we obtained these samples from kaggle where they had been reprocessed into 125Hz, therefore the sample above is (175/125) = roughly ~1.4 seconds. Hopefully this has been helpful (haven't thought about this for awhile haha)!

https://physionet.org/content/mitdb/1.0.0/
https://www.kaggle.com/datasets/shayanfazeli/heartbeat

**Comment by rdyan0053** [comment]
Thank you very much for your explanation
